spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
    hikari:
      maximum-pool-size: 300
      minimum-idle: 10
      connectionTimeout: 30000 #30s
      idleTimeout: 600000 #10 minutes
      maxLifetime: 1800000 #30 minutes
  jpa:
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  upload-dir: uploads/ # F:\\Work\\
springdoc:
  pathsToMatch: /api/**
#logging:
#  file:
#    path: /var/log
#    name: ${logging.file.path}/${spring.application.name}.log
